# Generated by Django 4.2.8 on 2023-12-12 05:12

from django.db import migrations, models
import exports.models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=exports.models.export_file_handler),
        ),
    ]
