# Generated by Django 4.2.8 on 2023-12-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
